### ISSUE TITLE
default to https if available

### ISSUE THREAD

**Issue by steveoh** [agrc/oil-gas-mining#1]
We are accessing the [utah plss](https://github.com/agrc/oil-gas-mining/blob/5435f64e00aa79de5cb17cbdcbde020ebfff4ab3/src/app/config.js#L23) service with http here. If someone accesses our site with https then that will break. arcgis online offers https so if you have the option use https.

There are other spots in the codebase that should be fixed as well.

**Comment by stdavis** [comment]
Actually (at least in Chrome) it appears that the ESRI API takes care of this issue:
![image](https://cloud.githubusercontent.com/assets/1326248/18204595/d62f5d50-70da-11e6-9d9f-5d4c8a05ac46.png)

But you're right. It should be cleaned up.

**Comment by steveoh** [comment]
Esri isn't going to fix the other instances where http is being used.

**Comment by stdavis** [comment]
You mean the links to external pages? I didn't think that was an issue when you navigating to another page.

**Comment by steveoh** [comment]
If they are external then :+1:  I'll go back to sleep now.
